import React from 'react';
import { View, Text, ScrollView, StyleSheet, Share, Alert } from 'react-native';
import { colors, font, spacing, radius, type } from '../../src/theme';
import { Card, SectionHeader, PrimaryButton, Chip } from '../../src/components';
import { getTrips, getRecords, getUser } from '../../src/db';
import { fmtGbp, fmtMiles, taxYearLabel, vehicleLabel } from '../../src/db/tax';

type Period = 'week' | 'month' | 'taxyear';

export default function ExportScreen() {
  const [period, setPeriod] = React.useState<Period>('taxyear');

  const user = getUser();
  const trips = getTrips(500);
  const records = getRecords(500);

  const totalMiles = trips.reduce((s, t) => s + t.miles, 0);
  const totalDeduction = trips.reduce((s, t) => s + t.deduction, 0);
  const totalEarnings =
    trips.reduce((s, t) => s + (t.earnings ?? 0), 0) +
    records.filter(r => r.record_type === 'income').reduce((s, r) => s + (r.amount ?? 0), 0);
  const totalExpenses = records.filter(r => r.record_type === 'expense').reduce((s, r) => s + (r.amount ?? 0), 0);

  function buildCsv(): string {
    const header = 'date,type,platform,vehicle,miles,deduction,earnings,amount,notes';
    const tripRows = trips.map(t =>
      `${t.started_at.slice(0, 10)},GPS trip,${t.platform},${t.vehicle},${t.miles.toFixed(2)},${t.deduction.toFixed(2)},${t.earnings ?? ''},, `
    );
    const recRows = records.map(r =>
      `${r.created_at.slice(0, 10)},${r.record_type},${r.platform ?? ''},, ,${r.deduction ?? ''},, ${r.amount ?? ''},${r.notes ?? ''}`
    );
    return [header, ...tripRows, ...recRows].join('\n');
  }

  async function shareCsv() {
    const csv = buildCsv();
    await Share.share({ message: csv, title: `Okkle export ${taxYearLabel()}.csv` });
  }

  // HMRC-style mileage log: dated rows of date, vehicle, miles, purpose, deduction.
  function buildMileageLog(): string {
    const header = 'Date,Vehicle,Platform (purpose),Miles,Rate note,Deduction (GBP)';
    const rows = trips
      .slice()
      .sort((a, b) => a.started_at.localeCompare(b.started_at))
      .map(t =>
        `${t.started_at.slice(0, 10)},${vehicleLabel(t.vehicle)},${t.platform} delivery,${t.miles.toFixed(1)},HMRC simplified,${t.deduction.toFixed(2)}`
      );
    const footer = `,,Total,${totalMiles.toFixed(1)},,${totalDeduction.toFixed(2)}`;
    return [header, ...rows, footer].join('\n');
  }

  async function shareMileageLog() {
    await Share.share({
      message: buildMileageLog(),
      title: `Okkle HMRC mileage log ${taxYearLabel()}.csv`,
    });
  }

  async function shareSummary() {
    const lines = [
      `Okkle — Tax year ${taxYearLabel()} summary`,
      `Vehicle: ${vehicleLabel(user?.vehicle ?? 'car')}`,
      ``,
      `Total earnings:     ${fmtGbp(totalEarnings)}`,
      `Total miles:        ${fmtMiles(totalMiles)}`,
      `Mileage deduction:  ${fmtGbp(totalDeduction)}`,
      `Expenses for review:${fmtGbp(totalExpenses)}`,
      ``,
      `Trips logged: ${trips.length}`,
      ``,
      `— Generated by Okkle. Estimates only, not tax advice.`,
    ];
    await Share.share({ message: lines.join('\n'), title: `Okkle summary ${taxYearLabel()}` });
  }

  return (
    <ScrollView style={s.screen} contentContainerStyle={s.content}>
      <Text style={s.heading}>Export</Text>
      <Text style={s.sub}>Share with your accountant for your Self Assessment</Text>

      <SectionHeader title="Period" />
      <View style={s.chips}>
        {([['week', 'This week'], ['month', 'This month'], ['taxyear', `Tax year ${taxYearLabel()}`]] as [Period, string][]).map(([k, label]) => (
          <Chip key={k} label={label} selected={period === k} onPress={() => setPeriod(k)} size="lg" />
        ))}
      </View>

      <Card style={s.summaryCard}>
        <View style={s.summaryRow}>
          <Text style={s.summaryLabel}>Earnings</Text>
          <Text style={s.summaryValue}>{fmtGbp(totalEarnings)}</Text>
        </View>
        <View style={s.summaryRow}>
          <Text style={s.summaryLabel}>Miles logged</Text>
          <Text style={s.summaryValue}>{fmtMiles(totalMiles)}</Text>
        </View>
        <View style={s.summaryRow}>
          <Text style={s.summaryLabel}>Mileage deduction</Text>
          <Text style={[s.summaryValue, { color: colors.brand }]}>{fmtGbp(totalDeduction)}</Text>
        </View>
        <View style={[s.summaryRow, { borderBottomWidth: 0 }]}>
          <Text style={s.summaryLabel}>Expenses for review</Text>
          <Text style={s.summaryValue}>{fmtGbp(totalExpenses)}</Text>
        </View>
      </Card>

      <SectionHeader title="Share options" />
      <Card style={{ gap: spacing.md }}>
        <View>
          <Text style={s.exportTitle}>Summary text</Text>
          <Text style={s.exportSub}>Plain text overview — great to paste into an email to your accountant</Text>
          <PrimaryButton label="Share summary" onPress={shareSummary} style={{ marginTop: spacing.sm }} />
        </View>
        <View style={s.divider} />
        <View>
          <Text style={s.exportTitle}>HMRC mileage log</Text>
          <Text style={s.exportSub}>Dated log of every trip (date, vehicle, purpose, miles, deduction) — the format HMRC expects</Text>
          <PrimaryButton label="Share mileage log" onPress={shareMileageLog} variant="ghost" style={{ marginTop: spacing.sm }} />
        </View>
        <View style={s.divider} />
        <View>
          <Text style={s.exportTitle}>CSV data</Text>
          <Text style={s.exportSub}>All records including GPS trips, earnings and expenses</Text>
          <PrimaryButton label="Share CSV" onPress={shareCsv} variant="ghost" style={{ marginTop: spacing.sm }} />
        </View>
      </Card>

      <View style={s.disclaimer}>
        <Text style={s.disclaimerText}>
          All data is stored only on your device. Okkle is a record-keeping tool — your accountant files your return and confirms all figures.
        </Text>
      </View>
    </ScrollView>
  );
}

const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  content: { padding: spacing.xl, paddingTop: 60, paddingBottom: 40 },
  heading: { ...type.screenTitle, marginBottom: 6 },
  sub: { ...type.body, color: colors.textSecondary, marginBottom: spacing.xl },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.lg },
  summaryCard: { marginBottom: spacing.xl },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.border },
  summaryLabel: { fontSize: 15, color: colors.textSecondary },
  summaryValue: { fontSize: 15, fontWeight: font.semibold, color: colors.textPrimary },
  exportTitle: { fontSize: 15, fontWeight: font.semibold, color: colors.textPrimary },
  exportSub: { fontSize: 13, color: colors.textSecondary, marginTop: 2, lineHeight: 19 },
  divider: { height: 1, backgroundColor: colors.border },
  disclaimer: { marginTop: spacing.xl, padding: spacing.lg, backgroundColor: colors.bgSoft, borderRadius: radius.md },
  disclaimerText: { ...type.small, lineHeight: 18, textAlign: 'center' },
});
